[tools]
"aqua:neovim/neovim" = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
go = "latest"
gojq = "latest"
kubectl = "latest"
node = "lts"
"npm:@openai/codex" = "latest"
"pipx:mitmproxy" = "latest"
pnpm = "latest"
starship = "latest"
stern = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"

[settings]

[settings.npm]
package_manager = "pnpm"

[env]
GOBIN = "{{env.HOME}}/go/bin"
