[tools]
"aqua:neovim/neovim" = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
"github:asciinema/agg" = "latest"
go = "latest"
gojq = "latest"
kubectl = "latest"
node = "lts"
"npm:@devcontainers/cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@zed-industries/claude-code-acp" = "latest"
"pipx:mitmproxy" = "latest"
pnpm = "10"
starship = "latest"
stern = "latest"
ttyd = "latest"
usage = "latest"
uv = "latest"
vhs = "latest"
yq = "latest"
zoxide = "latest"

[settings]

[settings.npm]
package_manager = "pnpm"

[env]
GOBIN = "{{env.HOME}}/go/bin"
