"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_status\
(fg:color_blue bg:color_bg3)\
$kubernetes\
$line_break\
$time\
$character"""

add_newline = false
username.disabled = false
palette = 'bluloco_light'
continuation_prompt = "::: "

[palettes.bluloco_light]
color_fg0 = '#373a41'
color_bg1 = '#f9f9f9'
color_bg3 = '#a0a1a7'
color_blue = '#275fe4'
color_aqua = '#27618d'
color_green = '#23974a'
color_orange = '#df631c'
color_purple = '#823ff1'
color_red = '#d52753'
color_yellow = '#df631c'

[palettes.bluloco_dark]
color_fg0 = '#ffffff'
color_bg1 = '#282c34'
color_bg3 = '#abb2bf'
color_blue = '#3691ff'
color_aqua = '#10b1fe'
color_green = '#3fc56b'
color_orange = '#df631c'
color_purple = '#9f7efe'
color_red = '#ff6480'
color_yellow = '#f9c859'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'


[aws]
style = "bold yellow"
format = '[ $symbol $profile ($region)]($style)'
symbol = ""

[aws.region_aliases]
us-east-1 = "use1"

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"
format = "[[](fg:color_orange bg:color_bg1)$path[](fg:color_orange bg:color_bg1)]($style)"
home_symbol = " "
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "bold fg:color_bg1 bg:color_orange"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = " /"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fill]
style = "bg:color_bg1"
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = ""
style = "bold fg:color_green"
format = '[ $symbol $branch]($style)'

[git_status]
disabled = false
stashed = "󰽂 "
conflicted = "[](fg:color_red)"
diverged = "[↕](fg:color_yellow)"
deleted = "[✘](fg:color_red)"
up_to_date = "[](fg:color_green)"
style = "bold fg:color_fg0"
format = '[( $all_status$ahead_behind)]($style)'

[golang]
symbol = " "
style = "bold blue"
format = '[ $symbol($version)]($style)'

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
format = "[[ ](fg:color_blue bg:color_bg1)$ssh_symbol$hostname[](fg:color_blue bg:color_bg1)]($style)"
ssh_only = true
ssh_symbol = " "
style = "bold fg:color_bg1 bg:color_blue"

[kubernetes]
disabled = false
format = '[( $symbol$context)( \($namespace\))]($style)'
style = "bg:color_bg1 fg:color_green"
symbol = "󱃾 "

[[kubernetes.contexts]]
context_pattern = ".*-(mer.*)-(?<name>prod.*)/kube-(?<user>.*)"
context_alias = "pci/$name/$user"
style = "bg:color_bg1 fg:color_red"

[[kubernetes.contexts]]
context_pattern = ".*-(mer.*)-(?<name>staging.*)/kube-(?<user>.*)"
context_alias = "pci/$name/$user"
style = "color_blue"

[[kubernetes.contexts]]
context_pattern = ".*-(?<name>prod.*)/kube-(?<user>.*)"
context_alias = "$name/$user"
style = "bg:color_bg1 fg:color_red"

[[kubernetes.contexts]]
context_pattern = '.*-(?<name>.*-\d+)/kube-(?<user>.*)'
context_alias = "$name/$user"
style = "bg:color_bg1 fg:color_green"

[[kubernetes.contexts]]
context_pattern = "none"
context_alias = ""
symbol = ""

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = ""
style = "bold fg:color_blue"
format = '[ $symbol( $version)]($style)'

[ocaml]
symbol = " "

[os]
disabled = false
format = "[ $symbol]($style)"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = "[ ](fg:#48B9C7)"
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pulumi]
disabled = false
format = '[ $symbol($stack)]($style)'

[python]
symbol = " "
format = '[$symbol( $version)](fg:color_orange)'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "
style = "bold blue"
format = '[ $symbol($version) ]($style)'

[scala]
symbol = " "

[shell]
disabled = false
# format = "[$path[](fg:color_orange bg:color_bg1)]($style)"
format = "[ [](fg:color_fg0 bg:color_bg1)[ $indicator](fg:color_orange bg:color_fg0)[](fg:color_fg0 bg:color_bg1) ]($style)"
nu_indicator = "nu"

[swift]
symbol = " "

[zig]
symbol = " "

[time]
disabled = false
time_format = "%R"
style = "bold fg:color_purple bg:color_bg1"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold bg:color_bg1 fg:color_green)'
error_symbol = '[ ](bg:color_bg1 fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
