# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
# TODO: create upgrade command to download and install latest gh version (thanks for the suggestion @bilyes)
aliases:
    create-auto-merge-pr: |
        !gh pr create && gh pr merge --auto --merge
    changelog: |
        !nu -c '
          gh release list --json name
          | from json
          | get name
          | par-each --keep-order { |name|
              gh release view $name --json name,body,author
              | from json
              | $"# ($in.name) by ($in.author.login)\n\n($in.body)"
          }
          | str join "\n"
        '
    download-latest-release: |
        !repo=${1:-cli/cli}; picked_asset=$(gh release view -R $repo --json assets -q ".assets[].name" \
          | fzf --prompt="Pick an asset to download: "); \
        test -n $picked_asset && echo "Downloading asset $picked_asset..." && gh release download -R $repo -p $picked_asset
    merge-and-delete-pr: |
        !gh pr merge --delete-branch && git pull
    pr watch-checks: pr checks --watch
    show-branch-protection: |
        !gh api graphql \
          -f query="$(curl -s https://gist.githubusercontent.com/duboisf/68fb6e22ac0a2165ca298074f0e3b553/raw/23c22a0f3922b812581684e2fbd7c6d5bb8f9532/operations.graphql)" \
          -f operationName=showBranchProtection \
          -F owner=:owner \
          -F repo=:repo
    switch-branch: |
        !picked_branch="$(git branch --list \
          | fzf --preview='echo; git log -20 --color --decorate ${-1}'
          )"
        test -n "$picked_branch" && git switch "$(echo "$picked_branch" | cut -c 3-)"
    # Args: <team-slug> <permission>
    # Permission can be one of: pull, triage, push, maintain, admin and custom repository role names, if the org defined any.
    repo add-permission: |
        !gh api /orgs/{owner}/teams/$1/repos/{owner}/{repo} -f permission=$2 \
          --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" 
    repo default-settings: |
        !gh api /repos/{owner}/{repo} -F has_issues=false -F has_projects=false -F has_wiki=false \
          --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" 
    repo fclone: |
        gh repo clone Flatbook/$1
    view-latest-release: |
        !repo=${1:-cli/cli}
        gh release view --repo $repo --json assets,body,publishedAt,tagName,name,url --template '
        # {{ .name }}

        {{ .url }}

        _Published {{ timeago .publishedAt }}_

        {{ .body }}

        {{- if ne (len .assets) 0 }}

        | Assets |
        | ---- |
        {{- range .assets }}
        | {{ .name }} |
        {{- end }}
        {{- end }}
        ' | glow -p -
version: "1"
