# hyprpaper config
#
# 1. Preload the image(s) you want to use:
# preload = /home/fred/Pictures/Wallpapers/my-wallpaper.png
#
# 2. Assign images to monitors. Use `,` for "all monitors":
# wallpaper = ,/home/fred/Pictures/Wallpapers/my-wallpaper.png
# wallpaper = eDP-1,/home/fred/Pictures/Wallpapers/laptop-wallpaper.png
#
# Optional:
# ipc = on               # respond to `hyprctl hyprpaper` commands
# splash = false
# splash_offset = 2.0
