background {
    monitor =
    color = rgba(0a0a0aff)
    blur_passes = 0
}

input-field {
    monitor =
    size = 320, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    outer_color = rgba(303030ff)
    inner_color = rgba(202020ff)
    font_color = rgba(d0d0d0ff)
    fade_on_empty = true
    placeholder_text = <i>Password…</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = rgba(d0d0d0ff)
    font_size = 90
    font_family = Sans
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(d0d0d0aa)
    font_size = 18
    font_family = Sans
    position = 0, -40
    halign = center
    valign = center
}
